### ISSUE TITLE
R3

### ISSUE THREAD

**Issue by anurag2k13** [Abhishekmishra-17/eb3_Mind-benders_queue-using-array#2]
Kindly do not change.remove the tag in .md file
Institute
Lab Name
Experiment Name
Aim
Theory
Procedure
Pre Test
Post Test
References

**Comment by DrSKPandey-17** [comment]
> Kindly do not change.remove the tag in .md file
> Institute
> Lab Name
> Experiment Name
> Aim
> Theory
> Procedure
> Pre Test
> Post Test
> References
All things are done as per requirement.
