### ISSUE TITLE
round 2 - story outline

### ISSUE THREAD

**Issue by sheetalsingh08** [Abhishekmishra-17/eb3_Mind-benders_queue-using-array#3]
story outline is not proper , start it from what this experiment is all about , what user will see overall in this experiment and then end it with the overall objective of your experiement, write all of these in 1 small para

**Comment by DrSKPandey-17** [comment]
> story outline is not proper , start it from what this experiment is all about , what user will see overall in this experiment and then end it with the overall objective of your experiment, write all of these in 1 small para

done...
